services:
  - type: web
    name: outreachpilotpro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_production:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: BASE_URL
        value: https://outreachpilotpro.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
    autoDeploy: true
    healthCheckPath: / 